// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// BookHandler is an autogenerated mock type for the BookHandler type
type BookHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx
func (_m *BookHandler) Create(ctx *gin.Context) {
	_m.Called(ctx)
}

// FindAll provides a mock function with given fields: ctx
func (_m *BookHandler) FindAll(ctx *gin.Context) {
	_m.Called(ctx)
}

// FindOneById provides a mock function with given fields: ctx
func (_m *BookHandler) FindOneById(ctx *gin.Context) {
	_m.Called(ctx)
}

// NewBookHandler creates a new instance of BookHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookHandler {
	mock := &BookHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
