// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	domain "gin-go-testing/model/domain"

	errs "github.com/rulyadhika/go-custom-err/errs"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// BookRepository is an autogenerated mock type for the BookRepository type
type BookRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, book
func (_m *BookRepository) Create(ctx *gin.Context, db *sql.DB, book *domain.Book) (*domain.Book, errs.CustomError) {
	ret := _m.Called(ctx, db, book)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Book
	var r1 errs.CustomError
	if rf, ok := ret.Get(0).(func(*gin.Context, *sql.DB, *domain.Book) (*domain.Book, errs.CustomError)); ok {
		return rf(ctx, db, book)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *sql.DB, *domain.Book) *domain.Book); ok {
		r0 = rf(ctx, db, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *sql.DB, *domain.Book) errs.CustomError); ok {
		r1 = rf(ctx, db, book)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errs.CustomError)
		}
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, db
func (_m *BookRepository) FindAll(ctx *gin.Context, db *sql.DB) ([]*domain.Book, errs.CustomError) {
	ret := _m.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Book
	var r1 errs.CustomError
	if rf, ok := ret.Get(0).(func(*gin.Context, *sql.DB) ([]*domain.Book, errs.CustomError)); ok {
		return rf(ctx, db)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *sql.DB) []*domain.Book); ok {
		r0 = rf(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *sql.DB) errs.CustomError); ok {
		r1 = rf(ctx, db)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errs.CustomError)
		}
	}

	return r0, r1
}

// FindOneById provides a mock function with given fields: ctx, db, bookId
func (_m *BookRepository) FindOneById(ctx *gin.Context, db *sql.DB, bookId uint) (*domain.Book, errs.CustomError) {
	ret := _m.Called(ctx, db, bookId)

	if len(ret) == 0 {
		panic("no return value specified for FindOneById")
	}

	var r0 *domain.Book
	var r1 errs.CustomError
	if rf, ok := ret.Get(0).(func(*gin.Context, *sql.DB, uint) (*domain.Book, errs.CustomError)); ok {
		return rf(ctx, db, bookId)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *sql.DB, uint) *domain.Book); ok {
		r0 = rf(ctx, db, bookId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *sql.DB, uint) errs.CustomError); ok {
		r1 = rf(ctx, db, bookId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errs.CustomError)
		}
	}

	return r0, r1
}

// NewBookRepository creates a new instance of BookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookRepository {
	mock := &BookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
